server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: authenticationService
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/**
        - id: fileStorageService
          uri: http://localhost:8082/
          predicates:
            - Path=/api/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"